export const CACHE_TAGS = {
  PUBLIC_THOUGHT: "PUBLIC:THOUGHT",
  PUBLIC_THOUGHT_COUNT: "PUBLIC:THOUGHT:COUNT",
  PUBLIC_THOUGHT_HIGHLIGHT: "PUBLIC:THOUGHT:HIGHLIGHT",
} as const;

export type CacheTag = (typeof CACHE_TAGS)[keyof typeof CACHE_TAGS];
