export const LETTERS_PER_PAGE = 10;
export const LETTER_REPLIES_PER_PAGE = 15;

export const LETTER_BODY_MIN_LENGTH = 5;
export const LETTER_BODY_MAX_LENGTH = 20_000;
export const LETTER_NAME_MIN_LENGTH = 2;
export const LETTER_NAME_MAX_LENGTH = 40;

export const LETTER_REPLY_MAX_LENGTH = 15_000;

export const LETTER_BODY_WARNING_THRESHOLD = 500;
export const LETTER_RECIPIENT_WARNING_THRESHOLD = 10;
export const LETTER_REPLY_WARNING_THRESHOLD = 500;
